### ISSUE TITLE
geotagged locations

### ISSUE THREAD

**Issue by deryagulcinubc** [ropensci/photosearcher#10]
Hi. I was able to see the geotagged photos as point shapefile in Arcmap just last month (I used "geotagged photos to points" tool of ArcMap). I used photosearcher again for a specific area and even I see the attribute table in Arcmap, I can not see the points. Could you please help me to figure it out?

**Comment by Dr-Nathan-Fox** [comment]
Hi, 

This issue is due to a change that occurs to the outputs when using a shape file. If no shape file is used the result have a lat and long col, if you search using a shape file the results have a geometry column that is a combination of both. Arcmap might not be able to read the geometry column. 

I will work on adding the lat long col back to the result if using a shape file.
